### ISSUE TITLE
Each iteration over sparse arrays incorrectly executes on deleted entries

### ISSUE THREAD

**Issue by BackupForce** [wycats/handlebars.js#1065] opened 2015-07-24 09:43 UTC
I got an arraydata like this { rocords:[{Number:'1',Name:'test1'},{Number:'2',Name:'test2},{Number:'3',Name:'test3}] };
registerHelper like this
Handlebars.registerHelper('link', function (options) {
        return '<p>' + options.fn(this) + this.Name +'</p>';
});
I delete array[1];
when registerHelper execute array[1], 'this' ponit window.
Its something wrong?

**Comment by kpdecker** [comment] 2015-08-01 20:35
I'm not clear what your issue is here and a live example would help us debug this in a much better fashion. Please create a jsfiddle showing us the unexpected behavior. The contributing doc links to a template that can be used for this.

**Comment by BackupForce** [comment] 2015-08-04 09:48
finally haha
http://jsfiddle.net/InoKu/5ybzdbye/1/

**Comment by kpdecker** [comment] 2015-08-04 14:31
Thanks for the fiddle, it looks like we are iterating over sparse arrays incorrectly. We need to check to see the field exists prior to running it as an undefined context is not supported (outside of javascript strict mode). Will be fixed in the next release.

**Closed** 2015-08-04 17:40 UTC
Labels: bug
