### ISSUE TITLE
webpack + require handlebars error

### ISSUE THREAD

**Issue by abhisekp** [wycats/handlebars.js#1174] opened 2016-01-26 06:50 UTC
I get the following error simply by using require handlebars. 

``` text
▶ webpack --display-modules   
Hash: bdb0fe35e2f8bde783e5
Version: webpack 1.12.12
Time: 116ms
         Asset     Size  Chunks             Chunk Names
bundle.main.js  2.82 kB       0  [emitted]  main
   [0] ./src/index.js 150 bytes {0} [built]
   [1] ./~/handlebars/lib/index.js 792 bytes {0} [built] [3 warnings] [3 errors]

WARNING in ./~/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in ./~/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in ./~/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

ERROR in ./~/handlebars/lib/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../dist/cjs/handlebars/compiler/printer in /home/abhisekp/MyProjects/JSApps/MadeWithLove-Webpack/node_modules/handlebars/lib
 @ ./~/handlebars/lib/index.js 9:14-64

ERROR in ./~/handlebars/lib/index.js
Module not found: Error: Cannot resolve module 'fs' in /home/abhisekp/MyProjects/JSApps/MadeWithLove-Webpack/node_modules/handlebars/lib
 @ ./~/handlebars/lib/index.js 17:11-24

ERROR in ./~/handlebars/lib/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../dist/cjs/handlebars in /home/abhisekp/MyProjects/JSApps/MadeWithLove-Webpack/node_modules/handlebars/lib
 @ ./~/handlebars/lib/index.js 7:17-50 
```

My **`index.js`**

``` js
var handlebars = require('handlebars');
```

My **`package.json`**

``` json
  "dependencies": {
    "handlebars": "^4.0.5"
  }
```

**Comment by benjeffery** [comment] 2016-02-04 00:19
As mentioned in #1102 adding the line
`"browser": "dist/handlebars.js",`
to handlebars' package.json solved this for me.

**Comment by craigpestell** [comment] 2016-04-19 20:23
I was able to solve this issue in my project without touching handlebars package.json.
I added to my project's package.json the following:
`"browser": {
    "handlebars": false
  },`

**Comment by methodbox** [comment] 2016-05-15 23:28
Sounds like a problem with Webpack, not Handlebars.
The normal default path for any node module core files is /node_modules/module_name/dist.

That's where a node app will assume they are located; this means Webpack is handling require(); differently than node.

**Comment by gilesbradshaw** [comment] 2016-07-01 10:57
I got round this with ..

````
resolve: {
    alias: {
       handlebars: 'handlebars/dist/handlebars.min.js'
    }
}
````

in my webpack config

**Comment by abhisekp** [comment] 2016-07-01 13:52
thanks @gilesbradshaw :+1: :smile:

**Comment by rafde** [comment] 2016-08-27 00:30
@abhisekp was this resolved? Please close if yes.

**Comment by abhisekp** [comment] 2016-08-27 00:38
@rafde I've not checked it but will closing this issue as the issue has been made clear and a clear solution is suggested.

Thanks for the reminder. :blush:

**Comment by nikit-cpp** [comment] 2016-10-24 21:25
issue still reproducing if I require handlebars:

var Handlebars = require('handlebars');
Handlebars.registerHelper('greet', function(name) {
            return 'Hello, name=' + name + '!';
});

**Comment by rafde** [comment] 2016-10-25 05:23
Seems like a problem with your setup since nobody else has this problem

**Comment by flyher** [comment] 2016-11-08 02:48
@gilesbradshaw 
Thank you very much!

**Comment by oocx** [comment] 2016-12-12 06:39
I also get this error when using handlebars with an Angular 2 CLI project. I can't change my webpack configuration because the Angular CLI team decided to hide webpack details from Angular CLI users and they don't officially support modifying the webpack configuration.

**Comment by realappie** [comment] 2017-05-11 12:45
@oocx You could just import the JS file from the node_modules folder like so 

```import 'handlebars/dist/handlebars.min.js';```

This works fine!

**Comment by swilliams-a3digital** [comment] 2017-10-20 07:09
To get this to work in an angular 4 project I had to do this:
import * as handleBars from 'handlebars/dist/handlebars';

normally I'd just do this:
import * as handleBars from 'handlebars';

The line above works fine in a typescript project in node, but not in angular 4.

HandleBars is the only project where I have to import like this.  It makes me concerned I'm going to have a issue down the road.  It seems like HandleBars does not play nice with angular's webpack.

**Comment by nknapp** [comment] 2017-10-20 09:24
I could have a look if anyone sets up a minimal example project that reproduces the issue. No promises as to the "when", though...

**Comment by JannicBeck** [comment] 2018-06-12 07:56
@swilliams-a3digital Getting `Could not find a declaration file for module` declare module 'handlebars' or adding @types/handlebars does not help. How did you solve this?

**Comment by seyfer** [comment] 2018-06-14 09:13
This is the best solution I have found
https://github.com/valtech-nyc/brookjs/blob/master/packages/brookjs/webpack.config.js#L39-L43
here https://github.com/pcardune/handlebars-loader/issues/110#issuecomment-358681867

Thanks to @mAAdhaTTah

**Comment by catamphetamine** [comment] 2018-08-13 17:32
This is retarded.
This `handlebars` library should have fixed this bug.
Yet they neglect and ignore.

The workaround is to replace:

```js
import Handlebars from 'handlebars'
```

with:
```js
import Handlebars from 'handlebars/dist/cjs/handlebars'
```

**Comment by nknapp** [comment] 2018-08-14 21:42
@catamphetamine if you have a good solution to this issue, you are welcome to file a pull request. As long as it doesn't break anything, I will merge and publish a new version. Things like `const Handlebars = require('handlebars')` in NodeJS and existing setups with older versions of webpack should still work.

**About the "Yet they neglect and ignore":**

The problem with handlebars is that there are not a lot collaborators and at the moment, as far as I can see, I am the only active one. Well, more or less active.  It 23:26 now and this is the time I usually come to work on my private projects, because I have a family a daytime job and other hobbies.

So when you write "Yet they neglegt and ignore", there isn't a lot of "they". There is almost certainly no "they" that is getting paid to work on this project. I help people, because it's fun to talk to people and because it is fun to solve problems, fix bugs and write tests. Because I'm using Handlebars myself in a couple of projects, and because it feels good to stand in the stage-light from time to time. But I don't feel that it is my *duty* to do so. So I pick the issues that I like, mostly the ones that are quick and clear.

So, if you are using Handlebars and you have a problem and noone is going to solve it, maybe you should try to contribute a solution yourself.

I'll reopen the issue though, because it does not seem to be solved.

**Comment by catamphetamine** [comment] 2018-08-15 07:33
> because it feels good to stand in the stage-light from time to time.

I'm doing opensource for fun too, though not as popular as your library.
And also for a line or two in my CV. Helps getting a better job.
I can see you not getting much out of it rather than just fun because it's not technically your project, like @nknapp/handlebars.js
You maintain it and @wycats gets all the credit as far as the URL bar goes.
Ok, at least now we know that this project is not so actively maintained anymore.
Still, it's used in many places, I guess.
For example, SendGrid recently launched "customizable templates" using this `handlebars` language.
https://sendgrid.com/blog/how-to-use-sendgrids-dynamic-templates-for-your-transactional-emails/
https://github.com/sendgrid/sendgrid-nodejs/issues/221

As for the solution, I'd say split the package into `handlebars` and `handlebars/register` like Babel did with their `babel` and `babel/register`.
They only install the `require()` hook when doing `import 'babel/register'`.
That would be a breaking change for another major version but I can see there most likely will be no such version.
You could also create (if you want) a file in root called something like `core.js` and then Webpack users would require `handlebars/core` instead of `handlebars/dist/cjs/handlebars`, and it should also be documented because otherwise no one would know that on Webpack they should use that file.
The creator of Webpack is also from Germany, so you should respect Webpack I guess.|
By the way, I wasn't referring specifically to you because you didn't leave a comment before in this issue.
I was referring to @methodbox and his comment:

> Sounds like a problem with Webpack, not Handlebars.

And @rafde  and his comment:

> Seems like a problem with your setup since nobody else has this problem

Your comment didn't claim Webpack being "wrong" or anything so no wrong words from your side:

> I could have a look if anyone sets up a minimal example project that reproduces the issue. No promises as to the "when", though...

You didn't say that "Webpack is wrong, close the issue" so your comments are ok.

**Comment by catamphetamine** [comment] 2018-08-15 07:40
@nknapp 
Anyway, `import Handlebars from 'handlebars/dist/cjs/handlebars'` works just fine and I think you don't need to change anything in the library.
Just maybe add a line to the README saying that "If you're using Webpack then `import Handlebars from 'handlebars/dist/cjs/handlebars'` instead of `import Handlebars from 'handlebars'`.
`import Handlebars from 'handlebars/dist/cjs/handlebars'` is fine and it works.

**Comment by camdagr8** [comment] 2019-05-09 18:28
```
import Handlebars from 'handlebars/dist/cjs/handlebars
```

Worked for me as of this comment. 

I agree with @catamphetamine though. 

Better documentation is worth a lot and it wouldn't kill anyone to add that line to the [installation page](https://handlebarsjs.com/installation.html). 

We all build great things and want people to use them. 

But guess what, if the documentation sucks... so does the project because no one but you will be able to understand it. 

And remember... people fear what they don't understand. 

-end rant-

I do however appreciate your efforts on the library. 
Being an open source dev is often a thankless and painful odyssey with very little reward.

**Comment by nknapp** [comment] 2019-05-15 21:07
Actually, I'm not trying to make people use Handlebars. I'm just trying to help people have already decided to use it. 

I am currently building a new documentation site (whenever I have some time left) and I will include it there.

**Comment by nknapp** [comment] 2020-04-05 03:25
Should be resolved in #1102

**Closed by nknapp** 2020-04-05 03:25 UTC

**Comment by EnnioWolsink** [comment] 2021-07-23 12:12
This comment from @gilesbradshaw at Jul 1, 2016 is still relevant today:
> I got round this with ..
> 
> ```
> resolve: {
>     alias: {
>        handlebars: 'handlebars/dist/handlebars.min.js'
>     }
> }
> ```
> 
> in my webpack config

To make this work in combination with Angular 12, I had to do the following:

- `npm i -D @angular-builders/custom-webpack`
- Make in `angular.json` the following changes:

From:

```json
"build": {
  "builder": "@angular-devkit/build-angular:browser",
```

To:
```json
"build": {
  "builder": "@angular-builders/custom-webpack:browser",
  ...
  "options": {
    "customWebpackConfig": {
      "path": "./custom-webpack.config.ts"
    },
    ...
  }
```

Note there would be other options as well. And you shouldn't literally place `...` in there of course ;).

Also change this: 

```json
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
```

To this:

```json
"serve": {
  "builder": "@angular-builders/custom-webpack:dev-server",
```

Finally, add custom-webpack.config.ts to your project root:

```typescript
import { Configuration } from 'webpack';

export default {
  resolve: {
    alias: {
       handlebars: "handlebars/dist/handlebars.min.js"
    }
  },
} as Configuration;
```

Be sure to check out the README of [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack) as there might be more changes you'd need to make in angular.json and the rest of your project.

I hope this helps someone!

**Comment by Maximaximum** [comment] 2021-08-10 14:07
Hm, strange to find out that this issue hasn't been fixed yet

**Comment by frankguo-dyedurham** [comment] 2021-12-31 00:50
I am using handlebars library in React Native project and running into the similar issue with the code:
`import Handlebars from 'handlebars'`

I replace it with the code below:
`import Handlebars from 'handlebars/dist/handlebars'`

It looks like it works now. Just try to give some other hints here for someone who runs into the issue.

BTW, `import Handlebars from 'handlebars/dist/cjs/handlebars'` doesn't work. I guess it is because the react native project doesn't use webpack.

**Comment by stevemk14ebr** [comment] 2022-03-23 13:47
I get this error with webpack 5 and I don't know why.

```
"dependencies": {
"handlebars": "^4.7.7",
}

import HandleBars from 'handlebars';
```

**Comment by jaylinski** [comment] 2022-03-23 15:14
@stevemk14ebr The `dist`-folder exists within the distributed npm-package.

If you want a browser-compatible version, you can try to import via `import Handlebars from 'handlebars/lib/handlebars';`.

You may still need to polyfill Node.js function since we didn't release the fix for https://github.com/handlebars-lang/handlebars.js/issues/1593 yet.

**Comment by satyajitnayk** [comment] 2023-09-22 05:20
> I got round this with ..
> 
> ```
> resolve: {
>     alias: {
>        handlebars: 'handlebars/dist/handlebars.min.js'
>     }
> }
> ```
> 
> in my webpack config

Thanks a lot @gilesbradshaw❤️. This solution is still relevant today👍🏻.

**Comment by patricknwanah** [comment] 2023-10-17 04:32
how do i get this handlebars.min.js file?

**Comment by patricknwanah** [comment] 2023-10-17 05:45
> I got round this with ..
> 
> ```
> resolve: {
>     alias: {
>        handlebars: 'handlebars/dist/handlebars.min.js'
>     }
> }
> ```
> 
> in my webpack config

what is handlebars/dist/handlebars.min.js. Is this the location npm installs the handlebar after you run npm install? This issue is break for me in github action and i am using rush which installs the packages in the temp folder that is ignored in the check in.

**Comment by jarpoole** [comment] 2024-03-04 18:49
For anyone trying to run handlebars within ts-node WITHOUT precompiling the templates (because, for example, you are using webpack's [`asset/source`](https://webpack.js.org/guides/asset-modules/) module) you can call `Object.freeze(require.extensions)` after you finish your setup to prevent handlebars from making further changes.

For example, running 

In a new file called `handlebars.js`:
```ts
const fs = require('fs');

require.extensions['.hbs'] = function (module, filename) {
  const content = fs.readFileSync(filename, { encoding: 'utf-8' });
  return module._compile(
    `module.exports = ${JSON.stringify(content)}`,
    filename,
  );
};

Object.freeze(require.extensions);
```

Now run `ts-node` and require the above file:
```bash
npx ts-node -r ./handlebars.js script.ts
```


@nknapp I strongly agree with https://github.com/handlebars-lang/handlebars.js/issues/1174#issuecomment-413117885 that the correct solution is to separate handlebars into two libs: `handlebars` and `handlebars/register` so that users can explicitly opt-in or out depending on their needs. I understand this would be a breaking change but I think it would avoid a lot of confusion going forward.
