### ISSUE TITLE
Please consider allowing configurable escaping

### ISSUE THREAD

**Issue by kevinoid** [wycats/handlebars.js#1175] opened 2016-02-04 19:34 UTC
First, thanks for writing/maintaining Handlebars.js.  I've used it on several projects and really like it.

In v4.0.0 and later, due to 83b8e846 (as discussed in #1114 and #1083) , `=` is now escaped to `&#x3D;`.  Although this is probably a good choice on the whole, it is causing issues for me.

My immediate issue is that SendGrid doesn't HTML-decode `href` attribute values before replacement in outgoing emails.  So templating `<a href="{{linkUrl}}">a link</a>` with `https://example.com/?utm_medium=email` yields `<a href="https://example.com/?utm_medium&#x3D;email">a link</a>` which gets replaced by SendGrid with a tracking URL that redirects to the unescaped `href` value.  Clearly their system is broken, but they have no plans to fix it and it is out of my control.  It's also likely not the only software which doesn't properly HTML-decode `href` values.

I am currently doing my own escaping and returning `SafeString`, but the amount of work to do this consistently is non-trivial.  It would be nice to have an easier option.

Since I always quote attribute values, the `=` escaping is not necessary and counter-productive for my uses.  Would you be willing to support an option to configure which characters are escaped, to accommodate differing needs/uses?  If so, I could work up a PR.

Thanks,
Kevin

**Comment by jbboehr** [comment] 2016-02-05 07:03
Have you tried monkey patching [Handlebars.escapeExpression](https://github.com/wycats/handlebars.js/blob/v4.0.5/lib/handlebars.runtime.js#L20)?

**Comment by kevinoid** [comment] 2016-02-05 14:35
@jbboehr That's an idea I hadn't tried.  Thanks!  I tend to stick to the public API to avoid maintenance issues, but if `Handlebars.escapeExpression` were documented as caller-assignable and changes to that behavior treated as API changes, that would be good enough for me.

**Comment by kpdecker** [comment] 2016-02-05 14:37
This or creating a handlebars environment with that specific override are the officially supported approach.

Something like:

```
let myInst = Handlebars.create();
myInst.escapeExpression = ...
myInst.compile(...);
```

Should work and avoid any potential global concerns (you might have to adjust that a bit, I haven't tested that directly)

**Comment by kevinoid** [comment] 2016-02-05 15:57
Great, thanks.  Is it documented somewhere that I missed?

**Comment by kpdecker** [comment] 2016-02-05 22:40
I'm not certain, but above would be some of it :)

As with any monkey patch I would recommend writing a test to verify that
it's actually working to protect yourself should the library change. At
this point I don't expect that given the maturity of handlebars, but it's
generally a practice I try to follow in my own projects.

**Comment by kevinoid** [comment] 2016-02-05 22:42
Fair enough.  Thanks @kpdecker and @jbboehr!

**Comment by yunyu** [comment] 2020-03-11 22:38
@nknapp As of 2020, this workaround has stopped working and https://github.com/wycats/handlebars.js/pull/1523 hasn't been merged, which means that this is not doable with the current release from NPM. Are there any plans to allow for this?

**Comment by nknapp** [comment] 2020-03-12 20:14
Can you tell me in which versions it has worked. I wasn't aware that this has been possible at all.

**Comment by yunyu** [comment] 2020-03-16 22:22
@nknapp I just tried version v4.0.5 (which was released before February 2016) and it worked.

**Comment by nknapp** [comment] 2020-03-17 05:39
@yunyu Please adjust this jsfiddle so that it works: If this is really a regression, I will fix it. But if it is a new feature, I need clarity for myself on how the interface should be. 

My problem is actually that none of the variants that I proposed in #1523 is really good. And monkey-patching is the worst kind of interface IMHO.

As an example, I tried to use a simple "toUpperCase" as escape-function. But the ways Kevin described it about does not work with 4.0.5 and it does not with 3.0.0

https://jsfiddle.net/uepx1cs9/3/

**Comment by yunyu** [comment] 2020-03-21 01:46
@nknapp See https://jsfiddle.net/po4sfy28/

**Comment by nknapp** [comment] 2020-03-22 19:28
I wouldn't recommend doing that as well. Globals shouldn't be changed.

I'm closing this in favour of #1523. But in the current situation, I cannot really do a lot of open source work (schools closed due to corona, supervise kids I'm addition to working from home, there's not much energy left right now)

**Closed by nknapp** 2020-03-22 19:28 UTC
