### ISSUE TITLE
 Uncaught TypeError: Cannot assign to read only property 'partial' of <partial name>

### ISSUE THREAD

**Issue by dougfarre** [wycats/handlebars.js#969] opened 2015-02-24 23:09 UTC
I upgraded my rails project from 4.1.8 to 4.2.0 and now I have this error:
 Uncaught TypeError: Cannot assign to read only property 'partial' of  <partial name> on the line below     options.partial = true;

__exports__.resolvePartial = resolvePartial;function invokePartial(partial, context, options) {
    options.partial = true;

    if(partial === undefined) {
      throw new Exception("The partial " + options.name + " could not be found");
    } else if(partial instanceof Function) {
      return partial(context, options);
    }
  }

Any suggestions on how to troubleshoot this so I can provide more information would be greatly helpful.  I don't even know where to begin.

**Comment by kpdecker** [comment] 2015-02-28 22:26
Can you create a jsfiddle or jsbin example demonstarting the issue?

**Comment by aalpern** [comment] 2015-02-28 23:02
I ran into exactly the same problem about 20 minutes ago, upgrading [tessera](https://github.com/urbanairship/tessera) to use handlebars 3.0. 

We use Grunt, and it appears to be an issue with using `grunt-contrib-handlebars` to compile the templates (see this issues - https://github.com/gruntjs/grunt-contrib-handlebars/issues/136).

**Comment by kpdecker** [comment] 2015-02-28 23:10
There was a breaking change in `invokePartial` in 3.x (thus the semver change) so that is a sensible explanation. @dougfarre closing this now assuming that root cause, but glad to reopen if you post a fiddle with a repo case.

**Closed by kpdecker** 2015-02-28 23:10 UTC
Labels: bug, unverified
