### ISSUE TITLE
Using triple braces to open and close html tags does not render properly

### ISSUE THREAD

**Issue by georges49** [wycats/handlebars.js#1261] opened 2016-10-07 09:26 UTC
In my controller javascript file I have the following:
`"openTag": "<div>",`
`"closeTag": "</div>"`
I want to be able to use them in my template like this:
`{{{openTag}}}`
`     ``<button type="button" class="btn btn-default" >Button</button>`
`{{{closeTag}}}`

The result I want is this:
`<div>`
`     ``<button type="button" class="btn btn-default" >Button</button>`
`</div>`

But instead it is rendering as this:
`<div></div>`
`<button type="button" class="btn btn-default" >Button</button>`

I want to run  an each loop inside the openTag but the problem is the tag is not always a div, it could be a `<span>, <p>, <section>, <ul>` or any other container tag, so I want it to be dynamic otherwise I have to insert an if block for each container.

**Comment by nknapp** [comment] 2016-10-09 11:29
Have you looked at the DOM or at the actual Handlebars output? Could you try to run `console.log()` with the result of the template-function? The browser might do some cleanups, although I don't understand why this should happen in your case.

**Comment by georges49** [comment] 2016-10-10 08:29
Thanks for your reply.
I looked at the DOM, I inspected the page.
Which function do you mean? I'm just using triple braces to render a string property as HTML like this `{{{openTag}}}`

**Comment by nknapp** [comment] 2016-10-10 11:47
[In the Contributing-Guide](https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md) there is a link to a [JSFiddle-Template](https://jsfiddle.net/9D88g/47/) that you can use to show your issue.
I have copied your Twiddle in the at https://jsfiddle.net/9D88g/53/ and it's working as you would expect.

This probably isn't a bug in Handlebars but something in Ember or even another package...

**Comment by georges49** [comment] 2016-10-10 15:05
That's really weird. If you look at the twiddle, there isn't a lot of packages.  It may be the ember-template-compiler.
Thanks a lot anyway.

**Comment by lawnsea** [comment] 2016-11-23 04:42
I'm going to close this. Please reopen if you have reason to suspect the issue is Handlebars.

**Closed by lawnsea** 2016-11-23 04:42 UTC
