### ISSUE TITLE
Custom Error Objects / Handlers / Messages

### ISSUE THREAD

**Issue by maikelmclauflin** [wycats/handlebars.js#1420] opened 2018-01-19 17:14 UTC
- [x] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [x] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [] Use the jsfiddle-template at https://jsfiddle.net/9D88g/47/ to reproduce problems or bugs

Hi all, this is more of a feature request than anything else, simply because I have been unable to find anything in documentation. I was wondering if it would be possible to extract more information out of parser errors instead of having to read and parse out a string. Is it possible to create an overwriteable logger function to for an individual like myself to create error messages and metadata as I see fit for the application that I am building? If it is already in there somewhere then that would be super helpful, but from what i saw when reading the parser, errors do not seem to go through a single point. If there are any ideas regarding this I would be happy to hear them.

**Comment by nknapp** [comment] 2020-04-05 04:51
Duplicate of #1173

**Closed by nknapp** 2020-04-05 04:51 UTC
